### ISSUE TITLE
"org.codehaus.mojo:license-maven-plugin:1.12" License error

### ISSUE THREAD

**Issue by LuckyCat17** [softwaremagico/KendoTournamentManager#181]
Hello guys, when i try to do "mvn clean install" in backend root i get this error:
```
"[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.12:update-file-header (first) on project kendo-tournament-backend: could not obtain the license repository: no licenses.properties found with url [file://C:/Users/Dario/Documents/KendoTournamentManager/backend/license/licenses.properties] for resolver org.codehaus.mojo.license.model.LicenseRepository@624d778e -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException"
```
How i can resolve this? thanks for help

**Comment by softwaremagico** [comment]
Hello @LuckyCat17. I am assuming that you are trying to compile the master branch. Clearly is looking for a file that must be there: `license/licenses.properties`. Can you check if it is there? As it is [on the repository](https://github.com/softwaremagico/KendoTournamentManager/blob/main/backend/license/licenses.properties) and must be downloaded when you have cloned it.

**Comment by LuckyCat17** [comment]
Hello sorry for the the late reply I was on vacation.
I check if i have the license.properties and i have it.
I tried to re-clone the repository but still got the same error.
![image](https://github.com/softwaremagico/KendoTournamentManager/assets/62267498/b94d36fb-ee7e-44dc-b681-4dcc1cf99607)

**Comment by softwaremagico** [comment]
Ok, then I will need some extra information. How are you compiling it? as the code is the same, if you are using the correct command must work fine. Please, share the command you are using for compiling to be sure that is the correct one. Also share with me the path where you are executing the command.

**Comment by softwaremagico** [comment]
Ok, to try to help. Access to the folder `KendoTournamentGeenrator/backend` and execute:

```
mvn clean install
```

Do you still have this error? If is the case, check that you do not have any error before the one you are reporting that can bring extra clarity.

**Comment by LuckyCat17** [comment]
Sorry for the late reply, the command you sent me was already the one I was using and it always gives  the error,
`PS C:\Users\Dario\Documents\KendoBackEnd\KendoTournamentManager\backend> mvn clean install       
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.softwaremagico:kendo-tournament-persistence:jar:2.12.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework.boot:spring-boot-starter-cache:jar -> duplicate declaration of version (?) @ line 50, column 21[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Kendo Tournament Manager                                           [pom]
[INFO] Kendo Tournament Manager (Logger)                                  [jar]
[INFO] Kendo Tournament Manager (Persistence)                             [jar]
[INFO] Kendo Tournament Manager (Core)                                    [jar]
[INFO] Kendo Tournament Manager (PDF)                                     [jar]
[INFO] Kendo Tournament Manager (Rest)                                    [jar]
[INFO]
[INFO] ------------< com.softwaremagico:kendo-tournament-backend >-------------
[INFO] Building Kendo Tournament Manager 2.12.0                           [1/6]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ kendo-tournament-backend ---
[INFO] Deleting C:\Users\Dario\Documents\KendoBackEnd\KendoTournamentManager\backend\target
[INFO]
[INFO] --- checkstyle:3.3.0:check (validate) @ kendo-tournament-backend ---
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO]
[INFO] >>> spotbugs:4.7.3.4:check (compile) > :spotbugs @ kendo-tournament-backend >>>
[INFO]
[INFO] --- spotbugs:4.7.3.4:spotbugs (spotbugs) @ kendo-tournament-backend ---
[INFO] 
[INFO] <<< spotbugs:4.7.3.4:check (compile) < :spotbugs @ kendo-tournament-backend <<<
[INFO]
[INFO]
[INFO] --- spotbugs:4.7.3.4:check (compile) @ kendo-tournament-backend ---
[INFO]
[INFO] --- license:2.0.1:update-file-header (first) @ kendo-tournament-backend ---
[INFO] Adding a license repository jar:file:/C:/Users/Dario/.m2/repository/org/codehaus/mojo/license-maven-plugin/2.0.1/license-maven-plugin-2.0.1.jar!/META-INF/licenses
[INFO] adding extra resolver file://C:\Users\Dario\Documents\KendoBackEnd\KendoTournamentManager\backend/license
[INFO] Adding a license repository file://C:/Users/Dario/Documents/KendoBackEnd/KendoTournamentManager/backend/license
[INFO] register GNU Free Documentation License (FDL) version 1.3
[INFO] register GNU General Lesser Public License (LGPL) version 3.0
[INFO] register GNU Affero General Public License (AGPL) version 3.0
[INFO] register GNU General Public License (GPL) version 3.0
[INFO] register GNU General Public License (GPL) version 2.0
[INFO] register GNU General Public License (GPL) version 1.0
[INFO] register Apache License version 2.0
[INFO] register Eclipse Public License - v 2.0 with Secondary License
[INFO] register Eclipse Public License - v 2.0
[INFO] register Eclipse Public License - v 1.0
[INFO] register Eclipse Public + Distribution License - v 1.0
[INFO] register COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0
[INFO] register GNU General Lesser Public License (LGPL) version 2.1
[INFO] register MIT-License
[INFO] register BSD 2-Clause License
[INFO] register BSD 3-Clause License
[INFO] register European Union Public License v1.1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kendo Tournament Manager 2.12.0:
[INFO]
[INFO] Kendo Tournament Manager ........................... FAILURE [  7.320 s]
[INFO] Kendo Tournament Manager (Logger) .................. SKIPPED
[INFO] Kendo Tournament Manager (Persistence) ............. SKIPPED
[INFO] Kendo Tournament Manager (Core) .................... SKIPPED
[INFO] Kendo Tournament Manager (PDF) ..................... SKIPPED
[INFO] Kendo Tournament Manager (Rest) .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.628 s
[INFO] Finished at: 2023-07-27T22:01:06+02:00
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING]
[WARNING]  * com.github.spotbugs:spotbugs-maven-plugin:4.7.3.4
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.1:update-file-header (first) on project kendo-tournament-backend: could not obtain the license repository: no licenses.properties 
found with url [file://C:/Users/Dario/Documents/KendoBackEnd/KendoTournamentManager/backend/license/licenses.properties] for resolver org.codehaus.mojo.license.model.LicenseRepository@464a3430 -> [Help 1][ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
PS C:\Users\Dario\Documents\KendoBackEnd\KendoTournamentManager\backend> `

**Comment by softwaremagico** [comment]
I do not see anything special in the way you compile. The only difference is that you are compiling on a Windows machine and I am not. Probably this explains why the file is not found. I need to test it on a Windows machine to have more information.

**Comment by softwaremagico** [comment]
Ok, I have changed the way that the license is provided to the system. Now is downloaded from a URL and no file is required any more. This must fix your issue. Please check on the branch `license-downloaded` and confirm if the issue persists in your computer or not.

**Comment by LuckyCat17** [comment]
i re-cloned the solution in new work space and the problem persist
ERROR CODE: 
`PS C:\Users\Dario\KendoTournamentManager\backend> mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.softwaremagico:kendo-tournament-persistence:jar:2.12.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework.boot:spring-boot-starter-cache:jar -> duplicate declaration of version (?) @ line 50, column 21[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Kendo Tournament Manager                                           [pom]
[INFO] Kendo Tournament Manager (Logger)                                  [jar]
[INFO] Kendo Tournament Manager (Persistence)                             [jar]
[INFO] Kendo Tournament Manager (Core)                                    [jar]
[INFO] Kendo Tournament Manager (PDF)                                     [jar]
[INFO] Kendo Tournament Manager (Rest)                                    [jar]
[INFO] 
[INFO] ------------< com.softwaremagico:kendo-tournament-backend >-------------
[INFO] Building Kendo Tournament Manager 2.12.0                           [1/6]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ kendo-tournament-backend ---
[INFO] Deleting C:\Users\Dario\KendoTournamentManager\backend\target
[INFO]
[INFO] --- checkstyle:3.3.0:check (validate) @ kendo-tournament-backend ---
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO]
[INFO] >>> spotbugs:4.7.3.4:check (compile) > :spotbugs @ kendo-tournament-backend >>>
[INFO]
[INFO] --- spotbugs:4.7.3.4:spotbugs (spotbugs) @ kendo-tournament-backend ---
[INFO] 
[INFO] <<< spotbugs:4.7.3.4:check (compile) < :spotbugs @ kendo-tournament-backend <<<
[INFO]
[INFO]
[INFO] --- spotbugs:4.7.3.4:check (compile) @ kendo-tournament-backend ---
[INFO] 
[INFO] --- license:2.0.1:update-file-header (first) @ kendo-tournament-backend ---
[INFO] Adding a license repository jar:file:/C:/Users/Dario/.m2/repository/org/codehaus/mojo/license-maven-plugin/2.0.1/license-maven-plugin-2.0.1.jar!/META-INF/licenses
[INFO] adding extra resolver file://C:\Users\Dario\KendoTournamentManager\backend/license
[INFO] Adding a license repository file://C:/Users/Dario/KendoTournamentManager/backend/license
[INFO] register GNU Free Documentation License (FDL) version 1.3
[INFO] register GNU General Lesser Public License (LGPL) version 3.0
[INFO] register GNU Affero General Public License (AGPL) version 3.0
[INFO] register GNU General Public License (GPL) version 3.0
[INFO] register GNU General Public License (GPL) version 2.0
[INFO] register GNU General Public License (GPL) version 1.0
[INFO] register Apache License version 2.0
[INFO] register Eclipse Public License - v 2.0 with Secondary License
[INFO] register Eclipse Public License - v 2.0
[INFO] register Eclipse Public License - v 1.0
[INFO] register Eclipse Public + Distribution License - v 1.0
[INFO] register COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0
[INFO] register GNU General Lesser Public License (LGPL) version 2.1
[INFO] register MIT-License
[INFO] register BSD 2-Clause License
[INFO] register BSD 3-Clause License
[INFO] register European Union Public License v1.1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kendo Tournament Manager 2.12.0:
[INFO]
[INFO] Kendo Tournament Manager ........................... FAILURE [  6.616 s]
[INFO] Kendo Tournament Manager (Logger) .................. SKIPPED
[INFO] Kendo Tournament Manager (Persistence) ............. SKIPPED
[INFO] Kendo Tournament Manager (Core) .................... SKIPPED
[INFO] Kendo Tournament Manager (PDF) ..................... SKIPPED
[INFO] Kendo Tournament Manager (Rest) .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.852 s
[INFO] Finished at: 2023-07-28T17:30:27+02:00
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING]
[WARNING]  * com.github.spotbugs:spotbugs-maven-plugin:4.7.3.4
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.1:update-file-header (first) on project kendo-tournament-backend: could not obtain the license repository: no licenses.properties found with url [file://C:/Users/Dario/KendoTournamentManager/backend/license/licenses.properties] for resolver org.codehaus.mojo.license.model.LicenseRepository@6f9a3325 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
PS C:\Users\Dario\KendoTournamentManager\backend> `

**Comment by softwaremagico** [comment]
But have you change the repository to the branch `license-downloaded`? From your error, seems that you are still compiling on the main branch. The change I have described belove is only available on the branch `license-downloaded` please, change your git branch executing `git checkout license-downloaded`.

**Comment by LuckyCat17** [comment]
Sorry my bad with the branch license-downloaded the mvn clean install works fine but the "mvn spring-boot:run" in the "backend\kendo-tournament-rest\target" not working..
`PS C:\Users\Dario\Documents\KendoTournamentManager-license-downloaded\backend\kendo-tournament-rest\target> mvn spring-boot:run
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.0/maven-install-plugin-3.1.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.0/maven-install-plugin-3.1.0.pom (7.8 kB at 31 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.0/maven-install-plugin-3.1.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/3.1.0/maven-install-plugin-3.1.0.jar (30 kB at 866 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/3.1.0/maven-deploy-plugin-3.1.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/3.1.0/maven-deploy-plugin-3.1.0.pom (8.9 kB at 201 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/3.1.0/maven-deploy-plugin-3.1.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/3.1.0/maven-deploy-plugin-3.1.0.jar (39 kB at 1.6 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.12.1/maven-site-plugin-3.12.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.12.1/maven-site-plugin-3.12.1.pom (20 kB at 904 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/36/maven-plugins-36.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/36/maven-plugins-36.pom (9.9 kB at 495 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.12.1/maven-site-plugin-3.12.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.12.1/maven-site-plugin-3.12.1.jar (119 kB at 3.4 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom (4.7 kB at 225 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom (12 kB at 587 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/9/maven-parent-9.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/9/maven-parent-9.pom (33 kB at 1.6 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar (24 kB at 1.1 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (15 kB at 722 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom (13 kB at 682 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar (209 kB at 5.1 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom (11 kB at 545 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom (11 kB at 569 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar (153 kB at 6.1 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 570 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (21 kB at 338 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.152 s
[INFO] Finished at: 2023-07-28T17:56:25+02:00
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-site-plugin:3.12.1
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Dario\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
PS C:\Users\Dario\Documents\KendoTournamentManager-license-downloaded\backend\kendo-tournament-rest\target>`

**Comment by softwaremagico** [comment]
Great! first thing solved. For executing, you can use directly a `java -jar kendo-tournament-backend.jar` if you are in the `target`folder already. The command `mvn sprin-boot:run` is for executing in the folder `backend\kendo-tournament-rest` not in the `target. 

Note that this will only execute the backend service.

**Comment by softwaremagico** [comment]
I mark this issue as resolved. For any different problem, please open a new one.
