### ISSUE TITLE
Feature request add Fusen-gachi

### ISSUE THREAD

**Issue by booji** [softwaremagico/KendoTournamentManager#426]
Just downloaded and been playing around with this app today.
Love what you are doing here!

I noticed that when doing scorekeeping there is no Fusen-gachi a win by default. 
The marks 〇 〇 are put on the winner side or you put one 〇 in case of Encho.

**Comment by softwaremagico** [comment]
Ok, I get it. In my club we also use `Ippon` for this king of things. 
It is not difficult to add it, then probably for next version I will add it.

**Comment by booji** [comment]
Ah right that makes sense was wondering what the `Ippon` one was for.
I can use that then while trying this out. Thanks!

**Comment by softwaremagico** [comment]
Probably in a few days I will release a new version. I will mantain both scores, and will be suitable for any club. No problem.
